[env:arduino_nano]
platform = atmelavr
board = nanoatmega328
framework = arduino

upload_protocol = arduino
upload_speed = 115200

monitor_speed = 115200

lib_deps = sui77/RC-Switch
build_flags =
    -Wall
    -Wextra
