[env:esp32]
platform = espressif32
board = esp32cam
framework = arduino

platform_packages =
  framework-arduinoespressif32
  framework-espidf

board_build.sdkconfig = sdkconfig.defaults
board_build.partitions = partitions.csv
board_build.flash_mode = dio

monitor_rts = 0
monitor_dtr = 0
upload_resetmethod = nodemcu

build_unflags = -std=gnu++11
build_flags =
  -std=gnu++17
  -DBOARD_HAS_PSRAM
  -DCORE_DEBUG_LEVEL=3
  ;-DCONFIG_ESP32_SPIRAM_SUPPORT=y
  ;-DCONFIG_ESP32_SPIRAM_USE_MALLOC=y

